# VM identity
vm_name: amine-ansible-vm02
vm_memory: 2048
vm_vcpus: 2
vm_disk_size: 20G


# Libvirt
libvirt_pool: amin-pool
libvirt_pool_dir: /mnt/storage/amin
libvirt_network: amin-net

# Cloud image
base_image_url: https://dl.rockylinux.org/pub/rocky/9/images/x86_64/Rocky-9-GenericCloud.latest.x86_64.qcow2
base_image_name: rocky9-base.qcow2

