# VM identity
vm_name: amine-ansible-vm02
vm_memory: 2048
vm_vcpus: 2
vm_disk_size: 20G


# Libvirt
libvirt_pool: amin-pool
libvirt_pool_dir: /mnt/storage/amin
libvirt_network: amin-net

# Cloud image
base_image_url: https://mirror.atl.adaptivedatanetworks.com/fedora/linux/releases/38/Cloud/x86_64/images/Fedora-Cloud-Base-38-1.6.x86_64.qcow2
base_image_name: fedora-base.qcow2

