# VM identity
vm_name: amine-ansible-vm02
vm_memory: 2048
vm_vcpus: 2
vm_disk_size: 20G


# Libvirt
libvirt_pool: amin-pool
libvirt_pool_dir: /mnt/storage/amin
libvirt_network: amin-net

# Cloud image
base_image_url: "https://mirror.atl.adaptivedatanetworks.com/fedora/linux/releases/38/Cloud/x86_64/images/Fedora-Cloud-Base-38-1.6.x86_64.qcow2"
vm_os_variant: "generic"

vm_arch: "x86_64"
vm_machine: "pc-i440fx-rhel7.6.0"
vm_clock: "utc"
# Graphics (set to 'none' for headless)
vm_graphics_type: "spice"
vm_graphics_listen: "127.0.0.1"
vm_cpu_mode: "host-model"
vm_features: ["acpi", "apic"]
vm_disk_format: "qcow2"