---
version: 3

images:
  base_image:
    name: quay.io/ansible/creator-ee:latest


dependencies:
  ansible_core:
    package_pip: ansible-core

  ansible_runner:
    package_pip: ansible-runner

  galaxy: requirements.yml
  python: requirements.txt

  system:
    - libvirt-client
    - libvirt-daemon
    - libvirt-daemon-driver-qemu
    - libvirt-daemon-config-network
    - virt-install
    - qemu-img
    - genisoimage
    - openssh-clients
    - rsync
    - sudo
    - libvirt-devel
    - gcc
    - sshpass
    - make
  
  post_build_commands:
    - mkdir ~/.ssh
    - ssh-keygen -t rsa -b 4096 -N '' -f .ssh/ocp4upi


options:
  package_manager_path: /usr/bin/microdnf
